# Generated by Django 5.2 on 2025-04-23 13:27

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='FangraphsHitterRange',
            fields=[
                ('player_id', models.IntegerField(primary_key=True, serialize=False)),
                ('player_name', models.CharField(max_length=255)),
                ('last_range', models.IntegerField()),
                ('team', models.CharField(blank=True, max_length=100, null=True)),
                ('range_wrcplus', models.DecimalField(blank=True, decimal_places=2, max_digits=5, null=True)),
                ('date_updated', models.DateTimeField(blank=True, null=True)),
            ],
            options={
                'db_table': 'baseball.FangraphsHitterRange',
            },
        ),
        migrations.CreateModel(
            name='FangraphsHitterSplits',
            fields=[
                ('player_id', models.IntegerField(primary_key=True, serialize=False)),
                ('player_name', models.CharField(max_length=255)),
                ('split', models.CharField(max_length=10)),
                ('team', models.CharField(blank=True, max_length=100, null=True)),
                ('wrcplus', models.DecimalField(blank=True, decimal_places=2, max_digits=5, null=True)),
                ('date_updated', models.DateTimeField(blank=True, null=True)),
            ],
            options={
                'db_table': 'baseball.FangraphsHitterSplits',
            },
        ),
        migrations.CreateModel(
            name='FangraphsPitcherSeason',
            fields=[
                ('player_id', models.IntegerField(primary_key=True, serialize=False)),
                ('player_name', models.CharField(max_length=255)),
                ('team', models.CharField(blank=True, max_length=100, null=True)),
                ('season', models.IntegerField(blank=True, null=True)),
                ('season_xfip', models.DecimalField(blank=True, decimal_places=2, max_digits=5, null=True)),
                ('date_updated', models.DateTimeField(blank=True, null=True)),
            ],
            options={
                'db_table': 'baseball.FangraphsPitcherSeason',
            },
        ),
        migrations.CreateModel(
            name='PitchingProbables',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('home_team', models.CharField(max_length=100)),
                ('away_team', models.CharField(max_length=100)),
                ('pitcher', models.CharField(max_length=100)),
                ('game_date', models.DateField()),
            ],
            options={
                'db_table': 'baseball.PitchingProbables',
                'unique_together': {('game_date', 'home_team', 'away_team')},
            },
        ),
    ]
