# Generated by Django 5.2 on 2025-04-23 13:27

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='FantasyAccountIdentifiers',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('platform', models.CharField(max_length=100)),
                ('sport', models.CharField(max_length=100)),
                ('account_id', models.CharField(max_length=100)),
                ('retrieve_id', models.CharField(max_length=255)),
            ],
            options={
                'db_table': 'main.FantasyAccountIdentifiers',
                'unique_together': {('platform', 'sport', 'account_id')},
            },
        ),
        migrations.CreateModel(
            name='FantasyLeague',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('account_id', models.CharField(max_length=255)),
                ('platform', models.CharField(max_length=50)),
                ('sport', models.CharField(max_length=50)),
                ('league_id', models.CharField(max_length=255)),
                ('league_name', models.CharField(max_length=255)),
                ('team_id', models.CharField(max_length=255)),
                ('team_name', models.CharField(max_length=255)),
            ],
            options={
                'db_table': 'main.FantasyLeague',
                'unique_together': {('account_id', 'platform', 'sport', 'league_id')},
            },
        ),
        migrations.CreateModel(
            name='FantasyPlayers',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('platform', models.CharField(max_length=50)),
                ('sport', models.CharField(max_length=50)),
                ('player_id', models.CharField(max_length=255)),
                ('name', models.CharField(max_length=255)),
                ('team', models.CharField(max_length=100)),
            ],
            options={
                'db_table': 'main.FantasyPlayers',
                'unique_together': {('platform', 'sport', 'player_id')},
            },
        ),
    ]
